# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtq_JEnHNP1bhSQPFCRtsWWmOl58gvpF
"""

text = "Hello Python Programming"
print(text)

print(text[0:5])   # First character
print(text[6:25])   # Character at index 6

print(text[0])   # First character
print(text[6])   # Character at index 6

print(text.upper())
print(text.lower())

print(text.capitalize())
print(text.title())

print("Python" in text)

print(text.find("Python"))

print(text.replace("Python", "Anaconda"))

text2 = "   Hello Anaconda   "
print(text2.strip())

words = text.split()
print(words)

joined_text = "-".join(words)
print(joined_text)

print(text.count("o"))

str1 = "Hi!"
str2 = "Anaconda"
print(str1 + " " + str2)

print(str1 * 3)

a = "Anaconda"
b = "python"

print(a == b)